import { CONFIG } from './config'

export const VALIDGUESSES = [
  'accent', 
  'bongos',
  'coucou',
  'djembe',
  'encore',
  'fouffe',
  'gitans',
  'hahaha',
  'ignare',
  'jacuzi',
  'kabyle',
  'louxor',
  'medley',
  'naines',
  'oompah',
  'putain',
  'quinte',
  'romain',
  'sonate',
  'tamtam',
  'unison',
  'vodkas',
  'whisky',
  'zigoto',
  'adrien',
  'betise',
  'cornet',
  'pixuli',
  'tonale',
  'timbre',
  'tomtom',
  'pierre',
  'amants',
  'violon',
  'bugles',
  'pinpon',
  'benoit',
  'basile',
  'tekila',
  'chloet',
  'titine',
  'phrase',
  'accord',
  'erwann',
  'france',
  'volume',
  'gypsie',
  'presto',
  'sextet',
  'sergio',
  'perrin',
  'accent',
  'oliver',
  'pedale',
  'tempos',
  'pompes',
  'piotre',
  'ballet',
  'thomas',
  'triade',
  'grunge',
  'gammes',
  'bemols',
  'triton',
  'chorus',
  'dieses',
  'entree',
  'finale',
  'doigte',
  'groove',
  'legato',
  'jammer',
  'mesure',
  'pimpom',
  'motifs',
  'fugues',
  'octave',
  'piston',
  'tuplet',
  'aubade',
  'arpege',
  'septet',
  'mihail',
  'nuance',
  'tampon',
  'mineur',
  'jerome',
  'majeur',
  'tuning',
  'vivace',
  'tenors',
  'pastis',
  'tetris',
  'bambin',
  'aviron',
  'copain',
  'vielle',
  'celine',
  'dreams',
  'gowest',
  'griego',
  'chatte',
  'adagio',
  'malika',
  'abaque', 'abatte', 'abattu', 'abbaye', 'abject', 'abjure', 'ablate', 'abolie', 'abolir', 'abolis', 'abonna', 'abonne', 'aborde', 'aboula', 'aboule', 'aboute', 'abouti', 
  'aboyai', 'aboyer', 'abrase', 'abrita', 'abrite', 'abroge', 'abrupt', 'abruti', 'absent', 'abside', 'absolu', 'absous', 'abusai', 'abuser', 'abusif', 'abysse', 
  'acabit', 'acacia', 'acajou', 'acarus', 'acaule', 'accent', 'accise', 'accole', 'accord', 'accore', 'accort', 'accota', 'accote', 'accoue', 'accroc', 'accrue', 
  'accrus', 'accule', 'accusa', 'accuse', 'acerbe', 'acheta', 'acheva', 'acinus', 'aconit', 'acquis', 'actais', 'actant', 'acteur', 'action', 'activa', 'active', 
  'actuel', 'adagio', 'adapta', 'adapte', 'adepte', 'adique', 'adirer', 'adjuge', 'adjure', 'admets', 'admire', 'admise', 'adonis', 'adonna', 'adonne', 'adopte', 
  'adorai', 'adorer', 'adossa', 'adosse', 'adoube', 'adroit', 'adulai', 'aduler', 'adulte', 'affala', 'affale', 'affame', 'affect', 'affile', 'affina', 'affine', 
  'affixe', 'afflux', 'affola', 'affole', 'affres', 'affure', 'afghan', 'afocal', 'agacer', 'agamie', 'agaric', 'agathe', 'agence', 'agenda', 'agirai', 'agisse', 
  'agitai', 'agiter', 'agneau', 'agonie', 'agonir', 'agonis', 'agouti', 'agrafe', 'agrile', 'agrion', 'agrume', 'aguets', 'ahanai', 'ahaner', 'ahurie', 'ahurir', 
  'ahuris', 'aidais', 'aidait', 'aidant', 'aident', 'aidera', 'aiglon', 'aigrie', 'aigrir', 'aigris', 'ailier', 'aillai', 'ailler', 'aimais', 'aimait', 'aimant', 
  'aiment', 'aimera', 'airain', 'airais', 'airbus', 'ajoure', 'ajouta', 'ajoute', 'ajusta', 'ajuste', 'alaire', 'alaise', 'alarma', 'alarme', 'alaska', 'albert', 
  'albite', 'albret', 'albugo', 'alcade', 'alcali', 'alcool', 'alcyne', 'alcyon', 'aldine', 'alerte', 'alevin', 'alexie', 'alexis', 'alezan', 'alfred', 'algide', 
  'algine', 'alicia', 'aligna', 'aligne', 'alisme', 'alitai', 'aliter', 'allais', 'allant', 'alliai', 'allier', 'alloue', 'alluma', 'allume', 'allyle', 'alogie', 
  'aloyau', 'alpaga', 'alpage', 'alpine', 'alsace', 'altier', 'altise', 'alunai', 'aluner', 'alunir', 'alunis', 'alvine', 'amadou', 'amande', 'amante', 'amaril', 
  'amarre', 'amassa', 'amasse', 'amatie', 'amatir', 'amatis', 'ambigu', 'amblai', 'ambler', 'ambrai', 'ambrer', 'amenai', 'amenda', 'amende', 'amener', 'amerri', 
  'ameute', 'amical', 'amidon', 'amiens', 'amiral', 'amnios', 'amocha', 'amoche', 'amodie', 'amoral', 'amorce', 'amorti', 'ampute', 'amurai', 'amurer', 'amusai', 
  'amuser', 'amusie', 'ananas', 'ancien', 'ancrai', 'ancrer', 'andain', 'andine', 'angers', 'angine', 'angkor', 'anglet', 'angola', 'angora', 'animai', 'animal', 
  'animer', 'anisai', 'aniser', 'ankara', 'annale', 'anneau', 'annecy', 'annexa', 'annexe', 'annone', 'annote', 'annuel', 'annula', 'annule', 'anobli', 'anodin', 
  'anomal', 'anomie', 'anorak', 'anordi', 'anosov', 'anoure', 'anurie', 'apache', 'apaisa', 'apaise', 'apeure', 'aphone', 'apical', 'apique', 'aplomb', 'aporie', 
  'aposte', 'appeau', 'appela', 'appert', 'apport', 'appose', 'appris', 'appuie', 'appuya', 'apside', 'apurai', 'apurer', 'aqueux', 'arabie', 'arable', 'araire', 
  'aramon', 'arasai', 'araser', 'arbore', 'arcade', 'arcane', 'arceau', 'archal', 'archer', 'archet', 'arcure', 'ardent', 'ardeur', 'argent', 'argile', 'arguai', 
  'arguer', 'arille', 'arioso', 'arisai', 'ariser', 'armada', 'armais', 'armait', 'armand', 'armant', 'arment', 'armera', 'armure', 'arnaud', 'arnica', 'aronde', 
  'arpent', 'arpion', 'arquai', 'arquer', 'arrhes', 'arrime', 'arrive', 'arrobe', 'arroge', 'arrose', 'arroyo', 'arsine', 'artois', 'arzela', 'ascite', 'ascoli', 
  'ashram', 'asiate', 'aspect', 'assaut', 'asseau', 'asseye', 'assidu', 'assied', 'assise', 'assoie', 'assois', 'assoit', 'assole', 'assuma', 'assume', 'assura', 
  'assure', 'astate', 'asthme', 'astral', 'astuce', 'ataxie', 'atonal', 'atonie', 'atours', 'atrium', 'atroce', 'attela', 'attend', 'attifa', 'attife', 'attire', 
  'attise', 'aubade', 'aubier', 'aubrac', 'auburn', 'aucuba', 'aucune', 'audace', 'audrey', 'augure', 'auquel', 'aurais', 'aurige', 'aurore', 'autant', 'auteur', 
  'autour', 'autrui', 'auvent', 'auxine', 'avalai', 'avaler', 'avance', 'avanie', 'avarie', 'avatar', 'avenir', 'avenue', 'averse', 'avilie', 'avilir', 'avilis', 
  'avinai', 'aviner', 'avions', 'aviron', 'avisai', 'aviser', 'avivai', 'aviver', 'avocat', 'avoine', 'avorte', 'avouai', 'avouer', 'axasse', 'axerai', 'axiale', 
  'axiome', 'axonge', 'azimut', 'azurai', 'azurer', 'azygos', 'babine', 'bachot', 'baffai', 'baffer', 'baffle', 'bafoue', 'bagage', 'bagdad', 'bagout', 'baguai', 
  'baguer', 'baigne', 'bailli', 'baisai', 'baiser', 'baisse', 'bajoue', 'balade', 'balaie', 'balane', 'balata', 'balaye', 'balcon', 'balise', 'ballai', 'baller', 
  'ballet', 'ballon', 'ballot', 'bamako', 'bambin', 'bambou', 'banach', 'banale', 'banane', 'banche', 'bandai', 'bander', 'bandit', 'banian', 'banlon', 'bannai', 
  'banner', 'bannir', 'bannis', 'banque', 'baobab', 'baquet', 'baraka', 'barbai', 'barber', 'barbet', 'barbon', 'barbue', 'bardai', 'barder', 'bardis', 'bardot', 
  'barman', 'barmen', 'baroud', 'barouf', 'barque', 'barrai', 'barrel', 'barrer', 'barrir', 'barris', 'barrot', 'baryon', 'baryte', 'baryum', 'basais', 'basale', 
  'basane', 'baside', 'basile', 'basket', 'basque', 'basset', 'bassin', 'basson', 'bastos', 'bateau', 'battis', 'battre', 'baudet', 'bauger', 'bauges', 'bavais', 
  'bavoir', 'bavure', 'bayais', 'beagle', 'beauce', 'becque', 'bectai', 'becter', 'bedeau', 'beigne', 'belize', 'belote', 'benzol', 'bercer', 'bergen', 'berlin', 
  'berlue', 'bernai', 'berner', 'besace', 'besant', 'besoin', 'bessel', 'beugle', 'beurre', 'bezout', 'biaise', 'bibine', 'biceps', 'bichai', 'bicher', 'bichof', 
  'bident', 'bidule', 'bielle', 'biface', 'biffai', 'biffer', 'biffin', 'bifide', 'bigame', 'biglai', 'bigler', 'bigote', 'bikini', 'bilais', 'bilame', 'bilbao', 
  'billet', 'billon', 'billot', 'bimane', 'binage', 'binais', 'binard', 'biniou', 'bipale', 'bipied', 'biplan', 'bisais', 'biseau', 'bishop', 'bisque', 'bissai', 
  'bissau', 'bisser', 'bistre', 'bistro', 'bitais', 'bitmap', 'bitord', 'bittai', 'bitter', 'bitume', 'biture', 'biveau', 'bizute', 'bizuth', 'blabla', 'blague', 
  'blaire', 'blaise', 'blasai', 'blaser', 'blason', 'blatte', 'blazer', 'blende', 'blesse', 'blette', 'bletti', 'bleuet', 'bleuir', 'bleuis', 'bleute', 'blinde', 
  'blocus', 'blonde', 'bloque', 'blouse', 'bluffe', 'blutai', 'bluter', 'bobard', 'bobine', 'bocage', 'bocard', 'bocaux', 'boette', 'boghei', 'boguet', 'boille', 
  'boirai', 'boisai', 'boiser', 'boitai', 'boiter', 'boitte', 'bolduc', 'bolide', 'bolier', 'bombai', 'bombay', 'bomber', 'bombyx', 'bonace', 'bonbon', 'bondai', 
  'bonder', 'bondir', 'bondis', 'bondon', 'bonite', 'bonnet', 'borate', 'bordai', 'bordel', 'border', 'borgne', 'bornai', 'borner', 'bornes', 'bossai', 'bosser', 
  'bossue', 'boston', 'bottai', 'botter', 'bottin', 'boubou', 'boucan', 'boucau', 'bouche', 'boucle', 'boudai', 'bouder', 'boudin', 'boueur', 'bouffe', 'bouger', 
  'bougie', 'bougre', 'boulai', 'bouler', 'boulin', 'boulon', 'boumer', 'bourbe', 'bourre', 'bourse', 'bousin', 'boutai', 'bouter', 'bouton', 'boutre', 'bouvet', 
  'boxais', 'boxeur', 'boyard', 'bradai', 'bradel', 'brader', 'braira', 'braire', 'braise', 'bramai', 'bramer', 'brande', 'brandy', 'branle', 'brante', 'braque', 
  'brasai', 'braser', 'brasse', 'brauer', 'bravai', 'braver', 'brayai', 'brayer', 'brebis', 'brelan', 'brelle', 'brelot', 'bresse', 'breton', 'brette', 'brevet', 
  'briard', 'bribes', 'bridai', 'brider', 'bridon', 'brifai', 'brifer', 'briffe', 'brigue', 'brimai', 'brimer', 'brique', 'brisai', 'briser', 'brisis', 'briska', 
  'broche', 'brodai', 'broder', 'bronze', 'brosse', 'brouet', 'broute', 'broyai', 'broyer', 'bruant', 'bruche', 'bruina', 'bruire', 'brumer', 'brunch', 'brunei', 
  'brunir', 'brunis', 'bryone', 'bubale', 'buccin', 'budget', 'buffet', 'buffle', 'bullai', 'buller', 'bunker', 'bureau', 'burgau', 'burine', 'busard', 'bushes', 
  'busque', 'butais', 'butane', 'buteur', 'butine', 'butoir', 'butome', 'buttai', 'butter', 'buvais', 'buvard', 'byssus', 'cabane', 'cabiai', 'cabine', 'cabrai', 
  'cabrer', 'cachai', 'cacher', 'cachet', 'cachot', 'cachou', 'cactus', 'caddie', 'cadeau', 'cadmie', 'cadrai', 'cadran', 'cadrat', 'cadrer', 'caecum', 'cafard', 
  'caftai', 'caftan', 'cafter', 'cageot', 'cagibi', 'cagnai', 'cagner', 'cagote', 'cahier', 'cahors', 'cahote', 'cahute', 'caille', 'caisse', 'cajole', 'calage', 
  'calais', 'calame', 'calcin', 'calcul', 'calfat', 'calice', 'calier', 'calife', 'calkin', 'calmai', 'calmar', 'calmer', 'calmir', 'calmis', 'calque', 'caltai', 
  'calter', 'camail', 'camais', 'cambre', 'camion', 'campai', 'camper', 'campos', 'campus', 'canada', 'canais', 'canard', 'canari', 'canaux', 'cancan', 'cancel', 
  'cancer', 'canche', 'cancre', 'candir', 'candis', 'cangue', 'canine', 'cannai', 'canner', 'canope', 'cantal', 'canter', 'canton', 'cantor', 'cantre', 'canule', 
  'canyon', 'capote', 'capron', 'captai', 'captal', 'capter', 'capuce', 'caquai', 'caquer', 'caquet', 'carabe', 'caraco', 'carafe', 'carcan', 'carcel', 'cardai', 
  'cardan', 'carder', 'cardia', 'cardon', 'cargue', 'cariai', 'carier', 'carine', 'carmai', 'carmer', 'carmin', 'carnet', 'carrai', 'carrer', 'cartan', 'cartel', 
  'carter', 'carton', 'casais', 'casbah', 'casher', 'casier', 'casino', 'casoar', 'casque', 'cassai', 'casser', 'cassis', 'casson', 'castel', 'castor', 'castre', 
  'cation', 'cauchy', 'cauris', 'causai', 'causer', 'causse', 'cavais', 'cavale', 'caveau', 'caviar', 'cayley', 'celais', 'cendre', 'centre', 'cercle', 'cerise', 
  'cernai', 'cerner', 'certes', 'cessai', 'cesser', 'cetera', 'cevita', 'ceylan', 'chable', 'chabot', 'chacal', 'chacun', 'chahut', 'chaire', 'chaise', 'chalet', 
  'chalut', 'champi', 'chance', 'chanci', 'change', 'chante', 'chapon', 'chaque', 'charge', 'charme', 'charte', 'chaste', 'chaton', 'chatte', 'chaude', 'chaule', 
  'chaume', 'chauve', 'chauvi', 'cheffe', 'cheikh', 'cheire', 'chelem', 'chemin', 'chenal', 'chenet', 'chenil', 'chenue', 'cherry', 'cheval', 'chevet', 'cheveu', 
  'chiade', 'chiais', 'chiche', 'chichi', 'chicon', 'chicot', 'chiffe', 'chiite', 'chimie', 'chinai', 'chiner', 'chintz', 'chipai', 'chiper', 'chipie', 'chique', 
  'chiton', 'chiure', 'chlore', 'choeur', 'chopai', 'choper', 'choque', 'chorus', 'chouan', 'choyai', 'choyer', 'christ', 'chrome', 'chromo', 'chrono', 'chutai', 
  'chuter', 'chypre', 'cierge', 'cigale', 'cigare', 'cilice', 'cillai', 'ciller', 'ciment', 'cimier', 'cincle', 'cingle', 'cintre', 'cipaye', 'cirage', 'cirais', 
  'cirque', 'cirrhe', 'cirrus', 'ciseau', 'cistre', 'citais', 'citron', 'citrus', 'civile', 'civita', 'clabot', 'claire', 'clamai', 'clamer', 'clampe', 'clapai', 
  'claper', 'clapet', 'clapir', 'clapis', 'claque', 'classe', 'claude', 'clause', 'clavai', 'claver', 'clayon', 'cligne', 'climat', 'clique', 'clisse', 'clivai', 
  'cliver', 'cloche', 'clonai', 'cloner', 'clorai', 'clouai', 'clouer', 'cloute', 'cobalt', 'cobaye', 'cobord', 'coccyx', 'cocker', 'cocyle', 'codage', 'codais', 
  'coffin', 'coffre', 'cogite', 'cogito', 'cognac', 'cognai', 'cognat', 'cogner', 'coiffe', 'coince', 'colite', 'collai', 'coller', 'collet', 'colley', 'colmar', 
  'colore', 'combat', 'combet', 'comble', 'comice', 'comics', 'commis', 'commue', 'compas', 'complu', 'compte', 'comput', 'condom', 'condor', 'confer', 'confie', 
  'confis', 'congre', 'congru', 'connus', 'conque', 'conrad', 'consul', 'contai', 'conter', 'contre', 'convie', 'convoi', 'coolie', 'coopte', 'copain', 'copeau', 
  'copiai', 'copier', 'coprah', 'coquai', 'coquer', 'corail', 'coraux', 'corbin', 'cordai', 'corder', 'cordon', 'cornac', 'cornai', 'corner', 'cornue', 'corozo', 
  'corpus', 'corral', 'corsai', 'corser', 'corset', 'cortex', 'coryza', 'cosmos', 'cossai', 'cosser', 'cossue', 'cotais', 'coteau', 'cotice', 'cotise', 'cotton', 
  'couche', 'coucou', 'coudai', 'couder', 'coudre', 'coulai', 'couler', 'coulis', 'coupai', 'couper', 'couple', 'coupon', 'courbe', 'courge', 'courir', 'course', 
  'courte', 'courus', 'cousis', 'coutil', 'coutre', 'couvai', 'couver', 'couvre', 'coxale', 'coyote', 'crabot', 'crache', 'cracra', 'crains', 'cramai', 'cramer', 
  'crampe', 'crante', 'craque', 'crasse', 'crawle', 'crayon', 'creuse', 'crevai', 'crever', 'criais', 'crible', 'cricri', 'crique', 'crispe', 'croate', 'croche', 
  'crocus', 'croire', 'croise', 'croque', 'crosse', 'crotte', 'croupe', 'croupi', 'cruche', 'crypte', 'cubage', 'cubais', 'cuesta', 'cuirai', 'cuisis', 'cuisse', 
  'cuitai', 'cuiter', 'cuivre', 'culais', 'cumule', 'cupide', 'cupule', 'curage', 'curais', 'curare', 'curium', 'cursus', 'curule', 'cutine', 'cutter', 'cuvage', 
  'cuvais', 'cuveau', 'cuvier', 'cynips', 'cyprin', 'cytise', 'dadais', 'daguai', 'daguer', 'daguet', 'dahlia', 'daigne', 'dakota', 'daleau', 'dallai', 'dallas', 
  'daller', 'dalton', 'damage', 'damais', 'damien', 'damier', 'damnai', 'damner', 'dandin', 'danger', 'daniel', 'dansai', 'danser', 'danube', 'dardai', 'darder', 
  'dartre', 'datage', 'datais', 'datcha', 'dation', 'dative', 'datura', 'daubai', 'dauber', 'davier', 'dealer', 'debout', 'dedans', 'dehors', 'demain', 'dengue', 
  'denise', 'denjoy', 'denver', 'depuis', 'design', 'desman', 'dessin', 'dessus', 'destin', 'devais', 'devant', 'devine', 'devins', 'devoir', 'devrai', 'dextre', 
  'diable', 'diacre', 'diapre', 'diaule', 'dictai', 'dicter', 'dicton', 'didier', 'didone', 'didyme', 'diesel', 'diffus', 'diktat', 'dilate', 'diluai', 'diluer', 
  'dindon', 'dinghy', 'dingue', 'dipode', 'dirham', 'dirhem', 'dirige', 'disais', 'dispos', 'disque', 'diurne', 'divine', 'divise', 'dizain', 'docile', 'docker', 
  'dodine', 'dogger', 'dolais', 'doleau', 'doline', 'dollar', 'dolman', 'dolmen', 'dombes', 'domine', 'domino', 'dompte', 'dondon', 'donjon', 'donnai', 'donner', 
  'dopage', 'dopais', 'doping', 'dorade', 'dorage', 'dorais', 'dormir', 'dormis', 'dorure', 'dosage', 'dosais', 'doseur', 'dotais', 'dotale', 'douais', 'douala', 
  'douane', 'double', 'douche', 'doucin', 'doucir', 'doucis', 'doutai', 'douter', 'dragon', 'drague', 'draine', 'drapai', 'draper', 'drayai', 'drayer', 'drelin', 
  'drenne', 'dresde', 'dresse', 'drille', 'drisse', 'drivai', 'driver', 'drogue', 'droite', 'dronte', 'dropai', 'droper', 'droppe', 'drosse', 'druide', 'dryade', 
  'dublin', 'ducale', 'ductus', 'duetto', 'dugong', 'duminy', 'dundee', 'dupais', 'duplex', 'duquel', 'durais', 'durant', 'durcir', 'durcis', 'durion', 'dynamo', 
  'dynkin', 'edmond', 'edwige', 'efface', 'effane', 'effare', 'effila', 'effile', 'effort', 'effroi', 'elaeis', 'elbeuf', 'embase', 'embats', 'embois', 'emboit', 
  'emboue', 'embout', 'embuai', 'embuer', 'emmure', 'empala', 'empale', 'empara', 'empare', 'empila', 'empile', 'empire', 'emplie', 'emplir', 'emplis', 'emploi', 
  'empois', 'emport', 'empote', 'empuse', 'encage', 'encart', 'encave', 'encens', 'encire', 'enclin', 'enclos', 'enclot', 'encode', 'encore', 'encrai', 'encrer', 
  'encule', 'encuve', 'encycl', 'endive', 'endors', 'endort', 'enduis', 'enduit', 'endure', 'enduro', 'enfant', 'enfila', 'enfile', 'enflai', 'enfler', 'enfuie', 
  'enfuir', 'enfuis', 'enfuma', 'enfume', 'engage', 'engame', 'engave', 'englue', 'engobe', 'engoua', 'engoue', 'enivra', 'enivre', 'enjoue', 'enlace', 'enleva', 
  'enliai', 'enlier', 'enlisa', 'enlise', 'ennemi', 'ennuie', 'ennuya', 'enquis', 'enrage', 'enraie', 'enraya', 'enraye', 'enrobe', 'enroua', 'enroue', 'ensile', 
  'ensuit', 'entais', 'entame', 'entend', 'entier', 'entoir', 'entour', 'entrai', 'entrer', 'entube', 'enture', 'envasa', 'envase', 'envers', 'enviai', 'envide', 
  'envier', 'envoie', 'envola', 'envole', 'envoya', 'enzyme', 'erbine', 'erbium', 'ermite', 'errais', 'errant', 'errata', 'erreur', 'ersatz', 'erseau', 'escale', 
  'escape', 'escaut', 'eschai', 'escher', 'escroc', 'escudo', 'espace', 'espada', 'espion', 'espoir', 'esprit', 'esquif', 'essaie', 'essaim', 'essart', 'essaya', 
  'essaye', 'essieu', 'essora', 'essore', 'essuie', 'essuya', 'estima', 'estime', 'estive', 'estran', 'ethnie', 'europe', 'evrard', 'evzone', 'exacte', 'exalta', 
  'exalte', 'examen', 'exauce', 'excave', 'excipe', 'excise', 'excita', 'excite', 'exclue', 'exclus', 'excusa', 'excuse', 'exempt', 'exerce', 'exhala', 'exhale', 
  'exhiba', 'exhibe', 'exhume', 'exiger', 'exilai', 'exiler', 'exocet', 'exonda', 'exonde', 'exorde', 'expert', 'expiai', 'expier', 'expire', 'exposa', 'expose', 
  'exquis', 'exsude', 'extase', 'facile', 'factum', 'fadais', 'fadeur', 'fading', 'fafiot', 'fagote', 'faible', 'faibli', 'faille', 'failli', 'faisan', 'falote', 
  'falune', 'falzar', 'famine', 'fanage', 'fanais', 'fanion', 'fanton', 'faquin', 'farcin', 'farcir', 'farcis', 'fardai', 'farder', 'farine', 'fartai', 'farter', 
  'fascia', 'fatale', 'fatras', 'fauber', 'fauche', 'faucon', 'faucre', 'faudra', 'faufil', 'fausse', 'fautai', 'fauter', 'favela', 'faveur', 'favori', 'faxais', 
  'fayard', 'feinte', 'fellah', 'feller', 'fendis', 'fendre', 'fennec', 'fenton', 'ferlai', 'ferler', 'fermai', 'fermat', 'fermer', 'ferrai', 'ferrer', 'ferret', 
  'fessai', 'fesser', 'fessue', 'festin', 'feston', 'feulai', 'feuler', 'feutre', 'fiable', 'fiacre', 'fiance', 'fiasco', 'fibule', 'fichai', 'ficher', 'fichet', 
  'fichue', 'fieffe', 'fierai', 'fiesta', 'figaro', 'figeai', 'figure', 'filage', 'filais', 'filmai', 'filmer', 'filtre', 'finage', 'finale', 'finish', 'firman', 
  'firmin', 'fiston', 'fistot', 'fixage', 'fixais', 'fixing', 'flache', 'flacon', 'flaire', 'flambe', 'flamme', 'flapie', 'flatte', 'flaupe', 'flegme', 'flemme', 
  'flette', 'fleure', 'fleuve', 'flipot', 'floche', 'flocon', 'florin', 'flotte', 'flouai', 'flouer', 'flouve', 'flouze', 'fluage', 'fluais', 'fluate', 'fluide', 
  'fluxai', 'fluxer', 'focale', 'foetus', 'foirai', 'foirer', 'foison', 'foliot', 'follet', 'foncer', 'fondai', 'fonder', 'fondis', 'fondre', 'fongus', 'fontis', 
  'forage', 'forais', 'forban', 'forcer', 'forcir', 'forcis', 'forfis', 'forger', 'forint', 'formai', 'format', 'former', 'formol', 'fortin', 'forure', 'fouace', 
  'fouage', 'foudre', 'foufou', 'fouger', 'fougue', 'foulai', 'fouler', 'foulon', 'fourbe', 'fourme', 'fourmi', 'fourre', 'foutez', 'foutra', 'foutre', 'foutue', 
  'fracas', 'fragon', 'fraise', 'france', 'franco', 'frange', 'frappe', 'frasil', 'frater', 'fraude', 'frayai', 'frayer', 'freine', 'frelon', 'fretin', 'frette', 
  'friche', 'fricot', 'frimai', 'frimas', 'frimer', 'fripai', 'friper', 'frirai', 'frisai', 'friser', 'fritte', 'froide', 'froidi', 'fronce', 'fronde', 'frotte', 
  'frouai', 'frouer', 'fruste', 'fubini', 'fubiny', 'fugace', 'fuguai', 'fuguer', 'fuient', 'fuirai', 'fumage', 'fumais', 'fumier', 'fumige', 'fumoir', 'fumure', 
  'fureur', 'furole', 'fusain', 'fusais', 'fuseau', 'fusion', 'futaie', 'futile', 'future', 'fuyais', 'gabare', 'gabbro', 'gabier', 'gabion', 'gadget', 'gadoue', 
  'gaetan', 'gaffai', 'gaffer', 'gageai', 'gagman', 'gagmen', 'gagnai', 'gagner', 'gainai', 'gainer', 'galbai', 'galber', 'galgal', 'galion', 'gallec', 'gallon', 
  'gallup', 'galois', 'galope', 'galure', 'gambie', 'gambit', 'gandin', 'gangue', 'gansai', 'ganser', 'gantai', 'ganter', 'garage', 'garais', 'gardai', 'garder', 
  'gardon', 'garnir', 'garnis', 'garrot', 'gasoil', 'gaston', 'gatien', 'gauche', 'gaucho', 'gaufre', 'gaulai', 'gauler', 'gaulis', 'gausse', 'gavage', 'gavais', 
  'gavial', 'gazage', 'gazais', 'gazole', 'gdansk', 'geisha', 'gelais', 'gelure', 'gemmai', 'gemmer', 'gendre', 'gentry', 'gerbai', 'gerber', 'gercer', 'germai', 
  'germen', 'germer', 'germon', 'getter', 'gevrey', 'geyser', 'ghetto', 'ghilde', 'giaour', 'gibbon', 'gibier', 'giboie', 'giclai', 'gicler', 'giflai', 'gifler', 
  'gigolo', 'gildas', 'gilles', 'gindre', 'ginkgo', 'girafe', 'gisais', 'gisant', 'gitane', 'givrai', 'givrer', 'glabre', 'glacer', 'glacis', 'glaire', 'glaise', 
  'glaive', 'glanai', 'glande', 'glaner', 'glapir', 'glapis', 'glaris', 'glatir', 'glatis', 'gliome', 'glisse', 'gloire', 'gloria', 'glosai', 'gloser', 'glotte', 
  'gluten', 'glycol', 'glyphe', 'gneiss', 'gnomon', 'gnosie', 'gobais', 'godage', 'godais', 'godron', 'goitre', 'golden', 'gomine', 'gommai', 'gommer', 'gonade', 
  'gondai', 'gonder', 'gonfle', 'gordon', 'gorfou', 'gorger', 'gorget', 'gosier', 'gospel', 'gouape', 'gouine', 'goujat', 'goujon', 'goulag', 'goulet', 'goulot', 
  'goulue', 'goupil', 'gourai', 'gourbi', 'gourde', 'gourer', 'gourme', 'gourou', 'gousse', 'goyave', 'grabat', 'graben', 'gracie', 'grader', 'gradin', 'gradue', 
  'gradus', 'graine', 'gramen', 'gramme', 'grande', 'grange', 'granit', 'graphe', 'grappe', 'grasse', 'gratin', 'gratis', 'gratte', 'gravai', 'graver', 'gravir', 
  'gravis', 'greffe', 'grelin', 'grelot', 'grenai', 'grenat', 'grener', 'grenue', 'grevai', 'grever', 'griffe', 'grigou', 'grigri', 'grille', 'grimai', 'grimer', 
  'grimpe', 'gringe', 'gringo', 'grippe', 'grisai', 'grisbi', 'griser', 'griset', 'grisou', 'groggy', 'grolle', 'gronde', 'grosse', 'grotte', 'groupe', 'grouse', 
  'gruger', 'guelfe', 'guelte', 'guenon', 'guerre', 'guette', 'gueule', 'gueuse', 'guibre', 'guiche', 'guidai', 'guider', 'guidon', 'guigne', 'guilde', 'guimpe', 
  'guinde', 'guipai', 'guiper', 'guipon', 'guizeh', 'gulden', 'gunite', 'guyane', 'habile', 'habite', 'hablai', 'habler', 'hachai', 'hacher', 'hachis', 'hadith', 
  'hadron', 'halage', 'hamada', 'hameau', 'hammam', 'hanche', 'hangar', 'hankel', 'hantai', 'hanter', 'happai', 'happer', 'haquet', 'hardai', 'harder', 'hardie', 
  'hareng', 'hargne', 'harpai', 'harper', 'harpie', 'harpon', 'hasard', 'hauban', 'hausse', 'hautin', 'havage', 'havais', 'havane', 'heaume', 'hennin', 'hennir', 
  'hennis', 'herbai', 'herber', 'herbue', 'hernie', 'hersai', 'herser', 'hetman', 'heurte', 'hexose', 'hiatal', 'hiatus', 'hideur', 'hilare', 'hilton', 'hindou', 
  'hippie', 'hircin', 'hissai', 'hisser', 'hochai', 'hocher', 'hochet', 'hockey', 'hoirie', 'homard', 'hombre', 'hongre', 'honnir', 'honnis', 'honora', 'honore', 
  'hoquet', 'horion', 'hormis', 'hostie', 'hottai', 'hotter', 'houais', 'houdan', 'houppe', 'houque', 'hourde', 'hourra', 'housse', 'hubert', 'hublot', 'huchai', 
  'hucher', 'huchet', 'huerai', 'huerta', 'hugues', 'huilai', 'huiler', 'hulule', 'humage', 'humain', 'humais', 'humble', 'humeur', 'humide', 'humour', 'hunier', 
  'hurlai', 'hurler', 'hurrah', 'hyalin', 'hydrie', 'hysope', 'ibadan', 'ibidem', 'icaque', 'icelle', 'icelui', 'idiome', 'idiote', 'idoine', 'idylle', 'ignace', 
  'igname', 'ignare', 'ignora', 'ignore', 'iguane', 'illico', 'imager', 'imamat', 'imanat', 'imbiba', 'imbibe', 'imitai', 'imiter', 'immola', 'immole', 'immune', 
  'impact', 'impair', 'impala', 'impoli', 'imposa', 'impose', 'impuni', 'impure', 'impute', 'inapte', 'incise', 'incite', 'inclus', 'incube', 'incuit', 'incuse', 
  'indexe', 'indice', 'indien', 'indigo', 'indium', 'indole', 'induis', 'induit', 'indult', 'indure', 'inepte', 'inerme', 'inerte', 'infant', 'infect', 'infime', 
  'infini', 'infixe', 'influx', 'infule', 'infuse', 'ingrat', 'ingrid', 'inhale', 'inhibe', 'inhume', 'inique', 'initia', 'initie', 'injure', 'innove', 'insane', 
  'insole', 'instar', 'intact', 'intime', 'intrus', 'intube', 'invita', 'invite', 'iodais', 'iodate', 'iodlai', 'iodler', 'ionien', 'ionise', 'ionone', 'ioulai', 
  'iouler', 'iourte', 'irisai', 'iriser', 'iritis', 'ironie', 'irrite', 'isatis', 'isolai', 'isoler', 'isopet', 'ispell', 'issant', 'isthme', 'italie', 'ivette', 
  'ivoire', 'ivraie', 'jabiru', 'jablai', 'jabler', 'jabote', 'jacket', 'jacobi', 'jactai', 'jaguar', 'jailli', 'jamais', 'jambon', 'jappai', 'japper', 'jardin', 
  'jardon', 'jargon', 'jarret', 'jasais', 'jasmin', 'jaspai', 'jasper', 'jauger', 'jaunir', 'jaunis', 'javart', 'javeau', 'jeanne', 'jensen', 'jerkai', 'jerker', 
  'jersey', 'jetage', 'jetais', 'jigger', 'jockey', 'jodlai', 'jodler', 'joncer', 'jonche', 'jongle', 'jonque', 'jordan', 'joseph', 'jouais', 'joujou', 'joutai', 
  'jouter', 'jouxte', 'juchai', 'jucher', 'judith', 'judoka', 'jugale', 'jugeai', 'jugule', 'jujube', 'julien', 'jumeau', 'jument', 'jungle', 'junior', 'junker', 
  'jurais', 'jureur', 'jusant', 'jusque', 'justin', 'jutais', 'kaboul', 'kabuki', 'kabyle', 'kaiser', 'kalium', 'kalman', 'kaluza', 'kamala', 'kanake', 'kanpur', 
  'kansas', 'kaolin', 'karbau', 'karman', 'kelvin', 'kentia', 'kepler', 'kesten', 'ketmie', 'khanat', 'kigali', 'kimono', 'kinase', 'kipper', 'kirsch', 'kitsch', 
  'klaxon', 'kobold', 'kopeck', 'koubba', 'koulak', 'koumis', 'koumys', 'kouros', 'koweit', 'kraken', 'kummel', 'kurosh', 'labeur', 'labile', 'labium', 'labour', 
  'labrit', 'lacune', 'ladies', 'ladite', 'laguis', 'lagune', 'lahore', 'lainai', 'lainer', 'laisse', 'laiton', 'laitue', 'lamais', 'lambda', 'lambel', 'lambic', 
  'lamier', 'lamine', 'lampai', 'lamper', 'lancer', 'landau', 'landes', 'landry', 'langer', 'langue', 'lanice', 'lanier', 'lapais', 'lapiaz', 'lapide', 'lapone', 
  'lapsus', 'laptot', 'laquai', 'laquer', 'larbin', 'larcin', 'lardai', 'larder', 'lardon', 'largue', 'larron', 'larynx', 'lascar', 'lassai', 'lasser', 'lassis', 
  'lastex', 'latine', 'latrie', 'lattai', 'latter', 'lattis', 'laudes', 'lavabo', 'lavage', 'lavais', 'lavoir', 'lavure', 'layais', 'lazare', 'leader', 'legato', 
  'lehmer', 'lendit', 'lequel', 'lerche', 'lestai', 'lester', 'letchi', 'lettre', 'leurre', 'levage', 'levain', 'levais', 'levier', 'levure', 'libage', 'libido', 
  'lichai', 'lichen', 'licher', 'licier', 'licite', 'lierai', 'lierne', 'lierre', 'liesse', 'lieuse', 'liftai', 'lifter', 'ligand', 'lignai', 'ligner', 'ligote', 
  'liguai', 'liguer', 'ligule', 'ligure', 'limace', 'limage', 'limais', 'limbes', 'limier', 'limite', 'limoge', 'limone', 'limule', 'lingam', 'linger', 'lingot', 
  'linter', 'lionne', 'lipase', 'lipide', 'lipome', 'lippue', 'lisage', 'lisais', 'lissai', 'lisser', 'listai', 'listel', 'lister', 'litais', 'litchi', 'liteau', 
  'litham', 'litige', 'litote', 'litron', 'litsam', 'livide', 'living', 'livrai', 'livrer', 'livret', 'llanos', 'loader', 'lobais', 'locale', 'lochai', 'locher', 
  'lofais', 'logeai', 'loggia', 'loiret', 'loisir', 'lokoum', 'lombes', 'longer', 'longue', 'loquai', 'loquer', 'loquet', 'lorgne', 'loriot', 'lorsqu', 'lotier', 
  'lotion', 'louage', 'louais', 'loubar', 'louchi', 'loufai', 'loufer', 'lougre', 'louise', 'loulou', 'loupai', 'louper', 'lourai', 'lourde', 'lourer', 'loutre', 
  'louvai', 'louver', 'louvre', 'lovais', 'loyale', 'luanda', 'lucane', 'lucide', 'lucien', 'ludion', 'luette', 'lugeai', 'luirai', 'luisis', 'lunule', 'lunure', 
  'lusaka', 'lustre', 'lutais', 'lutine', 'lutrin', 'luttai', 'lutter', 'luxais', 'luxure', 'luzule', 'lycaon', 'lychee', 'lycope', 'lycose', 'lymphe', 'lynche', 
  'lysais', 'lysine', 'maclai', 'macler', 'macque', 'macron', 'macule', 'madame', 'madone', 'madras', 'madrid', 'maffia', 'magnai', 'magnat', 'magner', 'magnum', 
  'magnus', 'magret', 'mahler', 'mahous', 'maigre', 'maille', 'mainte', 'mairie', 'maison', 'majore', 'malade', 'malaga', 'malard', 'malart', 'malawi', 'malaxe', 
  'malcev', 'malfis', 'malice', 'maltai', 'malter', 'manade', 'manage', 'manant', 'manche', 'mancie', 'mandai', 'mandat', 'mander', 'manger', 'mangue', 'maniai', 
  'manier', 'manioc', 'manoir', 'manque', 'maorie', 'maputo', 'maquai', 'maquer', 'maquis', 'marais', 'marbre', 'marcel', 'marfil', 'margay', 'marger', 'margis', 
  'mariai', 'marial', 'marier', 'marina', 'marine', 'marius', 'markov', 'marlou', 'marmot', 'marnai', 'marner', 'marque', 'marrai', 'marrer', 'marrie', 'martel', 
  'marthe', 'martin', 'martre', 'masque', 'massai', 'masser', 'massue', 'mastic', 'mastoc', 'masure', 'matage', 'matche', 'matoir', 'matras', 'maudis', 'maures', 
  'mauser', 'mauvis', 'maxima', 'maxime', 'mazout', 'mechta', 'mecque', 'mellin', 'membre', 'menace', 'menais', 'mendie', 'meneau', 'menhir', 'menine', 'menthe', 
  'mentir', 'mentis', 'menton', 'mentor', 'menuet', 'merise', 'merlan', 'merlin', 'merlon', 'messer', 'messie', 'mestre', 'mesure', 'mettre', 'meuble', 'meulai', 
  'meuler', 'meulon', 'mexico', 'miasme', 'michel', 'micmac', 'micron', 'mienne', 'miette', 'migrai', 'migrer', 'mijote', 'mikado', 'milice', 'milieu', 'millas', 
  'millau', 'millet', 'milord', 'mimais', 'mimosa', 'minage', 'minais', 'minbar', 'mincir', 'mincis', 'minima', 'minime', 'minium', 'minois', 'minore', 'minuit', 
  'minute', 'mioche', 'mirage', 'mirais', 'miroir', 'misais', 'missel', 'misses', 'mitage', 'mitais', 'mitige', 'mitose', 'mitron', 'mixage', 'mixais', 'mixeur', 
  'mobile', 'moblot', 'modale', 'module', 'modulo', 'moelle', 'moeurs', 'mohair', 'moirai', 'moirer', 'moisai', 'moiser', 'moisir', 'moisis', 'moitai', 'moiter', 
  'moitir', 'moitis', 'mollah', 'mollet', 'mollir', 'mollis', 'moloch', 'moment', 'monaco', 'monade', 'mondai', 'monder', 'montai', 'montel', 'monter', 'montre', 
  'moquai', 'moquer', 'morale', 'morbus', 'mordis', 'mordre', 'moreau', 'morera', 'morfil', 'morfle', 'morgue', 'morion', 'morita', 'morose', 'morula', 'mosane', 
  'moscou', 'motion', 'motive', 'mottai', 'motter', 'mouche', 'moudre', 'moufle', 'mouise', 'moujik', 'moulai', 'mouler', 'moulin', 'moulus', 'mourir', 'mouron', 
  'mourre', 'mourus', 'mouton', 'mouvai', 'mouver', 'muance', 'muchai', 'mucher', 'mucron', 'muerai', 'muette', 'muffin', 'muguet', 'muleta', 'munich', 'muphti', 
  'murage', 'murais', 'murale', 'murmel', 'musais', 'muscat', 'muscle', 'museau', 'musoir', 'musque', 'mussai', 'musser', 'mutage', 'mutais', 'mutile', 'mutine', 
  'mutule', 'mycose', 'mygale', 'myiase', 'myopie', 'myrrhe', 'nabote', 'nacrai', 'nacrer', 'naevus', 'nagata', 'nageai', 'nagoya', 'naisse', 'nandou', 'nankin', 
  'nantes', 'nantir', 'nantis', 'napalm', 'naphte', 'naples', 'nappai', 'napper', 'naquis', 'nargue', 'narine', 'narrai', 'narrer', 'narval', 'nasale', 'naseau', 
  'natale', 'natice', 'nation', 'native', 'natron', 'natrum', 'nattai', 'natter', 'nature', 'navaja', 'navale', 'navier', 'navire', 'navrai', 'navrer', 'nectar', 
  'neigea', 'neiger', 'nervin', 'nestor', 'neutre', 'nevers', 'newton', 'niable', 'niamey', 'nichai', 'nicher', 'nichet', 'nichon', 'nickel', 'nielle', 'nierai', 
  'nimbai', 'nimber', 'nimbus', 'nippai', 'nipper', 'nitrai', 'nitrer', 'nivale', 'niveau', 'nocher', 'nocive', 'nodale', 'nodule', 'nolise', 'nomade', 'nombre', 
  'nommai', 'nommer', 'nonidi', 'nopais', 'nordir', 'nordis', 'norois', 'nostoc', 'notais', 'notice', 'notion', 'notule', 'nouage', 'nouais', 'nougat', 'noulet', 
  'nounou', 'nouure', 'nouvel', 'novais', 'novice', 'noyade', 'noyais', 'nuance', 'nubile', 'nuerai', 'nuirai', 'nuisis', 'numide', 'nymphe', 'oasien', 'oblate', 
  'oblige', 'oblong', 'obscur', 'obtins', 'obture', 'obtuse', 'obvenu', 'obvers', 'obviai', 'obvier', 'obvins', 'obwald', 'occase', 'occlue', 'occlus', 'occupa', 
  'occupe', 'ocelle', 'ocelot', 'ocrais', 'ocreux', 'octane', 'octant', 'octave', 'octidi', 'octroi', 'octuor', 'oculus', 'odessa', 'odette', 'odieux', 'odilon', 
  'odorat', 'oedipe', 'oestre', 'office', 'offrir', 'offris', 'offset', 'ogival', 'ogonek', 'oignit', 'oignon', 'oindre', 'ointes', 'oisans', 'oiseau', 'oiseux', 
  'oisive', 'olympe', 'ombrai', 'ombrer', 'omette', 'omisse', 'omnium', 'onagre', 'oncial', 'ondine', 'ondoie', 'ondule', 'onglet', 'onglon', 'onques', 'onyxis', 
  'onzain', 'oocyte', 'oogone', 'opalin', 'opaque', 'ophite', 'ophrys', 'opiace', 'opimes', 'opinai', 'opiner', 'oppida', 'opposa', 'oppose', 'optais', 'optima', 
  'option', 'oracle', 'orante', 'orchis', 'ordure', 'oregon', 'orfroi', 'organe', 'orgeat', 'oribus', 'orient', 'origan', 'ormaie', 'ormeau', 'ormoie', 'ornais', 
  'oronge', 'orphie', 'orteil', 'orvale', 'osasse', 'oscule', 'oserai', 'osmium', 'osmose', 'osseux', 'ostiak', 'otarie', 'otique', 'ottawa', 'ouatai', 'ouater', 
  'oublia', 'oublie', 'ouille', 'oukase', 'ourdie', 'ourdir', 'ourdis', 'ourdou', 'ourlai', 'ourler', 'ourlet', 'oursin', 'ourson', 'outlaw', 'output', 'outrai', 
  'outrer', 'ouvert', 'ouvrai', 'ouvrer', 'ouvrir', 'ouvris', 'ouzbek', 'ovaire', 'ovibos', 'ovulai', 'ovuler', 'oxford', 'oxydai', 'oxyder', 'oxymel', 'oxyton', 
  'oxyure', 'pacage', 'pachto', 'pacque', 'pacson', 'padoue', 'paella', 'pageai', 'pageot', 'pagine', 'pagode', 'pagure', 'paille', 'pairie', 'pairle', 'pajote', 
  'palace', 'palais', 'pallie', 'palmai', 'palmer', 'palote', 'palpai', 'palper', 'palude', 'pampre', 'panade', 'panais', 'pandit', 'pannai', 'panner', 'pansai', 
  'panser', 'pansue', 'pantin', 'panure', 'panzer', 'paonne', 'papale', 'papaye', 'papier', 'papion', 'papule', 'paquet', 'parafe', 'parage', 'parais', 'pardon', 
  'parfis', 'parfum', 'pariai', 'parian', 'parier', 'parlai', 'parler', 'parole', 'paroli', 'parque', 'parsec', 'parsie', 'partir', 'partis', 'parton', 'parure', 
  'parvis', 'pascal', 'passai', 'passer', 'passim', 'pastel', 'pastis', 'patard', 'patate', 'pathos', 'patine', 'patodi', 'patois', 'patras', 'patrie', 'pattai', 
  'patter', 'pattue', 'paulin', 'paumai', 'paumer', 'pausai', 'pauser', 'pauvre', 'pavage', 'pavais', 'pavane', 'paveur', 'pavois', 'payais', 'pecnot', 'pecten', 
  'pehlvi', 'peigne', 'peille', 'peinai', 'peiner', 'pelade', 'pelage', 'pelais', 'pelard', 'pellet', 'pelote', 'pelure', 'pelvis', 'penche', 'pendis', 'pendre', 
  'pennon', 'pensai', 'penser', 'pensum', 'pentue', 'percer', 'perche', 'perdis', 'perdre', 'perlai', 'perler', 'perlon', 'perlot', 'permis', 'perron', 'persel', 
  'persil', 'pesade', 'pesage', 'pesais', 'peseta', 'pestai', 'pester', 'petite', 'peuple', 'peyotl', 'phanie', 'phasme', 'phobie', 'phonie', 'phoque', 'photon', 
  'phrase', 'phylum', 'pibale', 'picage', 'picard', 'pichet', 'picole', 'picolo', 'picore', 'picote', 'picris', 'pidgin', 'pierre', 'pieuse', 'pieute', 'pifais', 
  'piffai', 'piffer', 'pigeai', 'pignon', 'pilage', 'pilais', 'pilier', 'pillai', 'piller', 'pilori', 'pilote', 'pilule', 'piment', 'pinard', 'pincer', 'pineau', 
  'pingre', 'pinson', 'pintai', 'pinter', 'pinyin', 'pioche', 'piolet', 'pipais', 'pipeau', 'piquai', 'piquer', 'piraya', 'pirole', 'pissai', 'pissat', 'pisser', 
  'pistai', 'pister', 'pistil', 'piston', 'pistou', 'pivert', 'pivote', 'placer', 'plagie', 'plaide', 'plaine', 'plains', 'plaire', 'planai', 'planer', 'plante', 
  'plaque', 'plasma', 'plaste', 'platon', 'playon', 'pleine', 'pleure', 'pleuve', 'plexus', 'pleyon', 'pliage', 'pliais', 'plioir', 'plique', 'plisse', 'pliure', 
  'plombe', 'plonge', 'ploque', 'ployai', 'ployer', 'plumai', 'plumer', 'plumet', 'pluton', 'pneumo', 'pochai', 'pocher', 'pochon', 'podium', 'podzol', 'pognon', 
  'pogrom', 'poigne', 'poilai', 'poiler', 'poilue', 'pointe', 'poison', 'poisse', 'poitou', 'poivre', 'polder', 'police', 'pollen', 'pollue', 'polype', 'pommai', 
  'pommer', 'pompai', 'pomper', 'pompon', 'ponant', 'poncer', 'poncho', 'poncif', 'pondis', 'pondre', 'pontai', 'ponter', 'pontet', 'pontil', 'ponton', 'popote', 
  'populo', 'poquai', 'poquer', 'poquet', 'porche', 'porion', 'porque', 'portai', 'porter', 'portor', 'posada', 'posais', 'postai', 'poster', 'potage', 'potard', 
  'poteau', 'potion', 'poudre', 'poulet', 'poulie', 'poulpe', 'poumon', 'poupon', 'pousse', 'poutre', 'poutse', 'prague', 'praire', 'pralin', 'praxis', 'prends', 
  'presse', 'preste', 'presto', 'preuve', 'priais', 'primai', 'primer', 'prince', 'priori', 'prisai', 'prisca', 'priser', 'prisme', 'prison', 'privai', 'priver', 
  'proche', 'profil', 'profit', 'projet', 'prolan', 'promis', 'promus', 'pronom', 'propos', 'propre', 'proton', 'prouve', 'provin', 'proyer', 'pruine', 'prunus', 
  'prurit', 'prusse', 'psaume', 'pseudo', 'psoque', 'public', 'publie', 'puceau', 'pucier', 'puddle', 'pudeur', 'puerai', 'puffin', 'puisai', 'puiser', 'pulque', 
  'pulsai', 'pulsar', 'pulser', 'pureau', 'purger', 'purine', 'putain', 'putier', 'putiet', 'putois', 'putsch', 'puzzle', 'pyjama', 'pylore', 'pyrale', 'pyrite', 
  'pyrrol', 'pythie', 'python', 'pyurie', 'pyxide', 'quaker', 'quanta', 'quarre', 'quarte', 'quarto', 'quartz', 'quasar', 'quater', 'quatre', 'quelle', 'quercy', 
  'quiche', 'quidam', 'quille', 'quinoa', 'quinte', 'quinto', 'quinze', 'quipou', 'quitte', 'quitus', 'quorum', 'rabais', 'rabane', 'rabats', 'rabbin', 'rabiot', 
  'rabote', 'rachat', 'rachel', 'rachis', 'racine', 'racket', 'raclai', 'racler', 'racole', 'radais', 'radeau', 'radiai', 'radian', 'radier', 'radine', 'radium', 
  'radius', 'radjah', 'radoub', 'rafale', 'raffut', 'rafiot', 'raflai', 'rafler', 'rageai', 'raglan', 'raguai', 'raguer', 'raider', 'raidir', 'raidis', 'raille', 
  'rainai', 'rainer', 'raisin', 'raison', 'rajout', 'rallai', 'raller', 'rallie', 'rallye', 'ramage', 'ramais', 'ramdam', 'rameau', 'ramier', 'ramone', 'rampai', 
  'ramper', 'ramure', 'ranche', 'rancio', 'rancir', 'rancis', 'ranger', 'ranime', 'rapace', 'raphia', 'rapide', 'rapine', 'rappel', 'raquai', 'raquer', 'rasade', 
  'rasage', 'rasais', 'rashes', 'rasoir', 'rassis', 'raster', 'ratage', 'ratais', 'ratine', 'ration', 'rature', 'ravage', 'ravale', 'ravier', 'ravine', 'ravise', 
  'ravive', 'ravoir', 'rayage', 'rayais', 'rayure', 'razzia', 'razzie', 'rebats', 'rebond', 'rebord', 'rebute', 'recale', 'recase', 'recife', 'recoin', 'recole', 
  'record', 'recors', 'recrue', 'recrus', 'rectum', 'recule', 'redent', 'redore', 'redoux', 'refile', 'reflet', 'reflex', 'reflux', 'refuge', 'refuse', 'regain', 
  'regard', 'reggae', 'regrat', 'regret', 'rehaut', 'reiten', 'rejoue', 'rejuge', 'relaie', 'relais', 'relate', 'relave', 'relaxe', 'relaye', 'relent', 'reliai', 
  'relief', 'relier', 'reloge', 'reloue', 'remake', 'remise', 'remous', 'remuai', 'remuer', 'renaud', 'rendis', 'rendre', 'renfle', 'reniai', 'renier', 'rennes', 
  'renoue', 'rentai', 'renter', 'rentre', 'renvie', 'renvoi', 'repaie', 'repave', 'repaye', 'repens', 'replie', 'report', 'repose', 'requin', 'requis', 'resale', 
  'ressac', 'ressui', 'restai', 'rester', 'retape', 'retard', 'retire', 'retors', 'retour', 'revers', 'revins', 'revote', 'rhodia', 'rhombe', 'rhovyl', 'rhumai', 
  'rhumer', 'riblai', 'ribler', 'riblon', 'ribose', 'ribote', 'riccie', 'rictus', 'ridage', 'ridais', 'rideau', 'ridoir', 'ridule', 'rieuse', 'riffle', 'rififi', 
  'riflai', 'rifler', 'rigide', 'rigolo', 'rikiki', 'rilsan', 'rimais', 'rimaye', 'rimmel', 'rincer', 'riotai', 'rioter', 'ripage', 'ripais', 'ripper', 'risban', 
  'risque', 'rivage', 'rivais', 'rivale', 'rivoir', 'rivure', 'robage', 'robais', 'robert', 'rocade', 'rocher', 'rochet', 'rocker', 'rocket', 'rococo', 'rocoue', 
  'rodage', 'rodoir', 'rognai', 'rogner', 'rognon', 'rohart', 'roidir', 'roidis', 'roland', 'romain', 'romane', 'romani', 'romano', 'rompis', 'rompre', 'rondel', 
  'rondin', 'rondir', 'rondis', 'ronger', 'ronron', 'roquai', 'roquer', 'rosace', 'rosage', 'rosais', 'rosbif', 'roseau', 'rosine', 'rossai', 'rosser', 'rostre', 
  'rotais', 'rotang', 'rotary', 'rotule', 'roture', 'rouage', 'rouais', 'rouble', 'rouchi', 'rouget', 'rougir', 'rougis', 'roulai', 'rouler', 'roulis', 'roupie', 
  'rourke', 'rousse', 'routai', 'router', 'rouvre', 'rowing', 'royale', 'ruanda', 'rubane', 'rubato', 'ruchai', 'rucher', 'rudoie', 'ruelle', 'ruerai', 'ruffin', 
  'rufian', 'ruilai', 'ruiler', 'ruinai', 'ruiner', 'rumeur', 'rumine', 'rurale', 'rusais', 'rushes', 'russie', 'rustre', 'rwanda', 'rythme', 'sabbat', 'sabine', 
  'sablai', 'sabler', 'sablon', 'sabord', 'sabote', 'sabrer', 'sachem', 'sachet', 'sachez', 'sacome', 'sacque', 'sacrai', 'sacrer', 'sacret', 'sacrum', 'safari', 
  'safran', 'sagace', 'sagaie', 'saigne', 'saille', 'sainte', 'saisir', 'saisis', 'saison', 'salace', 'salade', 'salage', 'salais', 'salami', 'salaud', 'saline', 
  'salmis', 'saloir', 'saloon', 'salope', 'saluai', 'saluer', 'salure', 'samare', 'samedi', 'sampan', 'sampot', 'samson', 'sandow', 'sandre', 'sangle', 'santal', 
  'santon', 'saoule', 'sapais', 'sapeur', 'saphir', 'sapide', 'sapine', 'saquai', 'saquer', 'sarcle', 'sarong', 'sarrau', 'sarthe', 'sassai', 'sasser', 'satake', 
  'satane', 'satine', 'satire', 'sature', 'satyre', 'saucer', 'saumon', 'saumur', 'saunai', 'sauner', 'saurai', 'saurer', 'saurin', 'saurir', 'sauris', 'sautai', 
  'sauter', 'sauvai', 'sauver', 'savais', 'savane', 'savart', 'savate', 'saveur', 'savoie', 'savoir', 'scalde', 'scalpe', 'scampi', 'scande', 'scelle', 'schako', 
  'scheik', 'schleu', 'schupo', 'schuss', 'sciage', 'sciais', 'scille', 'scinde', 'scirpe', 'sciure', 'scolex', 'scolie', 'sconse', 'scopie', 'scorie', 'scotch', 
  'scotie', 'scoute', 'scribe', 'scrute', 'scutum', 'scythe', 'sebkha', 'secoue', 'seguia', 'seiche', 'seidel', 'seigle', 'seille', 'sellai', 'seller', 'semais', 
  'semoir', 'semple', 'senior', 'sentir', 'sentis', 'septum', 'sequin', 'sermon', 'serrai', 'serran', 'serrer', 'sertir', 'sertis', 'serval', 'servir', 'servis', 
  'setier', 'setter', 'severi', 'sevrai', 'sevrer', 'seyait', 'shaker', 'sherry', 'shimmy', 'shogun', 'shoote', 'shunte', 'sialis', 'sicile', 'siegel', 'sienne', 
  'sierra', 'sieste', 'siffle', 'signai', 'signal', 'signer', 'signet', 'silice', 'sillet', 'sillon', 'silphe', 'silure', 'silves', 'simili', 'simone', 'simoun', 
  'simple', 'simule', 'singer', 'single', 'sinise', 'siphon', 'sirdar', 'siroco', 'sirote', 'sistre', 'situai', 'situer', 'sixain', 'sizain', 'sketch', 'skiais', 
  'skunks', 'slalom', 'slavon', 'slogan', 'smashe', 'smilax', 'smiley', 'smille', 'smocks', 'sniffe', 'snobai', 'snober', 'socque', 'sodium', 'sodoku', 'soient', 
  'soigne', 'soldai', 'solder', 'soleil', 'solfie', 'solide', 'solive', 'somite', 'sommai', 'sommer', 'sommes', 'sommet', 'sonate', 'sondai', 'sonder', 'songer', 
  'sonnai', 'sonner', 'sonore', 'sophie', 'sorbet', 'sorgho', 'sortir', 'sortis', 'souche', 'soucie', 'soudai', 'soudan', 'souder', 'soufre', 'soulte', 'soumis', 
  'soupai', 'souper', 'soupir', 'souple', 'souque', 'source', 'sourde', 'sourie', 'souris', 'sourit', 'soviet', 'soyons', 'spalax', 'sparte', 'spasme', 'spathe', 
  'speech', 'speiss', 'sperme', 'sphinx', 'spider', 'spitte', 'spleen', 'spline', 'spolie', 'sprint', 'squale', 'squame', 'square', 'squash', 'squire', 'stable', 
  'stadia', 'staffe', 'stalag', 'stalle', 'stance', 'starie', 'stator', 'statue', 'statut', 'stawug', 'stayer', 'steppe', 'sterne', 'stiple', 'stocke', 'stoker', 
  'stolon', 'stoppe', 'storax', 'strass', 'strate', 'stress', 'striai', 'strier', 'strige', 'string', 'stroma', 'strume', 'stryge', 'studio', 'stupre', 'stuque', 
  'stylai', 'styler', 'stylet', 'styrax', 'suaire', 'subite', 'subito', 'succin', 'sucrai', 'sucrer', 'sucrin', 'suerai', 'suette', 'suffis', 'suifai', 'suifer', 
  'suiffe', 'suinte', 'suisse', 'suivis', 'suivre', 'summum', 'surate', 'surdos', 'sureau', 'surfai', 'surfer', 'surfil', 'surfis', 'surgir', 'surgis', 'surine', 
  'surjet', 'surlie', 'surmoi', 'surnom', 'sursis', 'survie', 'survis', 'survit', 'survol', 'suture', 'svelte', 'sydney', 'sylphe', 'sylvie', 'syndic', 'synode', 
  'syrinx', 'syrphe', 'tabard', 'tablai', 'tablar', 'tabler', 'tacaud', 'tacite', 'taenia', 'taille', 'tairai', 'tajine', 'talais', 'talent', 'taleth', 'talion', 
  'tallai', 'taller', 'talmud', 'talque', 'talure', 'talweg', 'tamier', 'tamise', 'tampon', 'tanaka', 'tancer', 'tanche', 'tandem', 'tandis', 'tangon', 'tanguy', 
  'tanise', 'tanker', 'tannai', 'tanner', 'tannin', 'tanrec', 'tapais', 'tapote', 'taquai', 'taquer', 'taquet', 'tarage', 'tarais', 'tarama', 'tarare', 'taraud', 
  'tarbes', 'tardai', 'tarder', 'targue', 'targui', 'tarife', 'tarpan', 'tarpon', 'tarski', 'tartan', 'tartir', 'tartis', 'tartre', 'tarzan', 'tassai', 'tasser', 
  'tatami', 'tatane', 'tatare', 'tatoue', 'taudis', 'taupin', 'tauzin', 'taxais', 'taylor', 'teckel', 'teille', 'teinte', 'telson', 'temple', 'tenace', 'tenais', 
  'tender', 'tendis', 'tendon', 'tendre', 'tennis', 'tenrec', 'tenson', 'tentai', 'tenter', 'tenure', 'tenuto', 'tercer', 'tercet', 'tergal', 'ternir', 'ternis', 
  'terrai', 'terrer', 'terril', 'terrir', 'terris', 'tersai', 'terser', 'tertio', 'tertre', 'tessin', 'tesson', 'testai', 'tester', 'teston', 'texane', 'thaler', 
  'thalle', 'thomas', 'thorax', 'thoron', 'thrips', 'thymie', 'thymol', 'thymus', 'thyrse', 'ticket', 'tienne', 'tierce', 'tietze', 'tiglon', 'tigrai', 'tigrer', 
  'tigron', 'tillac', 'tillai', 'tiller', 'timbre', 'timide', 'timing', 'tincal', 'tintai', 'tinter', 'tintin', 'tipule', 'tiquai', 'tiquer', 'tirade', 'tirage', 
  'tirais', 'tirana', 'tiroir', 'tisais', 'tisane', 'tissai', 'tisser', 'titane', 'titrai', 'titrer', 'toaste', 'tocade', 'tocsin', 'toilai', 'toiler', 'toisai', 
  'toiser', 'toison', 'tolite', 'toluol', 'tomais', 'tomate', 'tombac', 'tombai', 'tomber', 'tonale', 'tondis', 'tondre', 'tonner', 'tonton', 'topais', 'topaze', 
  'tophus', 'toquai', 'toquer', 'toquet', 'torche', 'torcol', 'tordis', 'tordre', 'torero', 'tories', 'torque', 'tortil', 'tortis', 'tortue', 'totale', 'touage', 
  'touais', 'toubib', 'toucan', 'touche', 'toueur', 'touffe', 'toulon', 'toupet', 'toupie', 'touque', 'touret', 'tourie', 'tourne', 'touron', 'tourte', 'toutim', 
  'toutou', 'toxine', 'tracas', 'tracer', 'tracte', 'trafic', 'trahir', 'trahis', 'traire', 'traite', 'trajet', 'tramai', 'tramer', 'transe', 'trappe', 'trapue', 
  'traque', 'trauma', 'trayon', 'treize', 'trempe', 'trente', 'tresse', 'treuil', 'triade', 'triage', 'triais', 'tribut', 'tricot', 'trigle', 'trimai', 'trimer', 
  'triode', 'triple', 'tripot', 'trique', 'trisme', 'trisoc', 'trisse', 'triste', 'triton', 'troche', 'trogne', 'trolle', 'trombe', 'trompe', 'troque', 'trotte', 
  'trouai', 'trouer', 'troupe', 'trouve', 'troyes', 'truble', 'truffe', 'truite', 'trulli', 'trullo', 'truque', 'truste', 'tuable', 'tubage', 'tubais', 'tudieu', 
  'tuerai', 'tuerie', 'tueuse', 'tufeau', 'tuilai', 'tuiler', 'tulipe', 'tumeur', 'tungar', 'tunnel', 'tupaja', 'turban', 'turbeh', 'turbin', 'turbot', 'turion', 
  'turnep', 'turque', 'tussah', 'tussor', 'tuthie', 'tutoie', 'tympan', 'typais', 'typhon', 'typhus', 'typise', 'ulrich', 'ultime', 'ultimo', 'ululai', 'ululer', 
  'umlaut', 'unguis', 'uniate', 'uniaxe', 'unifia', 'unifie', 'unique', 'unirai', 'unisse', 'unitif', 'uraeus', 'uranie', 'urbain', 'urgent', 'urgera', 'urinai', 
  'urinal', 'uriner', 'urique', 'ursule', 'usager', 'usante', 'usasse', 'userai', 'usinai', 'usiner', 'usurpe', 'utopie', 'vaccin', 'vacive', 'vacuum', 'vaguai', 
  'vaguer', 'vaigre', 'vaincs', 'vairon', 'valais', 'valeur', 'valgus', 'valide', 'valine', 'valise', 'vallon', 'valoir', 'valois', 'valsai', 'valser', 'vampai', 
  'vamper', 'vannai', 'vanner', 'vantai', 'vanter', 'vapeur', 'vaquai', 'vaquer', 'varech', 'variai', 'varice', 'varier', 'varlet', 'varron', 'vasque', 'vautre', 
  'veille', 'veinai', 'veiner', 'velche', 'venais', 'vendis', 'vendre', 'veneur', 'venger', 'venise', 'venter', 'ventis', 'ventre', 'verdet', 'verdir', 'verdis', 
  'verger', 'vergne', 'vergue', 'verjus', 'verlan', 'vermet', 'vermis', 'vernir', 'vernis', 'verrai', 'verrat', 'verrou', 'verrue', 'versai', 'verser', 'verset', 
  'verste', 'versus', 'vertex', 'vesoul', 'vessai', 'vesser', 'vessie', 'veston', 'vexais', 'viable', 'viaduc', 'viande', 'vibord', 'vibrai', 'vibrer', 'viciai', 
  'vicier', 'victor', 'vidage', 'vidais', 'vidame', 'vidime', 'vidoir', 'vidure', 'vienne', 'vierge', 'vigile', 'vignot', 'viking', 'vinage', 'vinais', 'vinyle', 
  'violai', 'violat', 'violer', 'violon', 'vioque', 'vioqui', 'viorne', 'virage', 'virago', 'virais', 'virale', 'vireur', 'virile', 'virion', 'virole', 'virose', 
  'virure', 'visage', 'visais', 'viseur', 'vision', 'visite', 'vissai', 'visser', 'vitale', 'vitali', 'vitrai', 'vitrer', 'vivace', 'vivais', 'vivent', 'vivien', 
  'vivier', 'vivrai', 'vivres', 'vocale', 'vogoul', 'voguai', 'voguer', 'voilai', 'voiler', 'voirie', 'voisin', 'volage', 'volais', 'volcan', 'volige', 'volley', 
  'voltai', 'volter', 'volume', 'volute', 'volvox', 'vorace', 'vortex', 'vosges', 'votais', 'votive', 'vouais', 'voulus', 'voyais', 'vrille', 'vrombi', 'vulpin', 
  'wading', 'wagage', 'wallis', 'walter', 'wapiti', 'waring', 'waters', 'watson', 'welche', 'welter', 'whisky', 'wiener', 'wigner', 'wigwam', 'wilaya', 'wombat', 
  'woofer', 'xemacs', 'yamabe', 'yankee', 'yaourt', 'yeoman', 'yeomen', 'yourte', 'youyou', 'ysopet', 'yttria', 'yvette', 'zagreb', 'zambie', 'zancle', 'zenana', 
  'zestai', 'zester', 'zeugma', 'zeugme', 'zibais', 'zieute', 'zigoto', 'ziguai', 'ziguer', 'zigzag', 'zingue', 'zinnia', 'zinzin', 'zippai', 'zipper', 'zircon', 
  'zombie', 'zonage', 'zonais', 'zonale', 'zonier', 'zonure', 'zouave', 'zurich', 'zwanze', 'zygoma', 'zygote', 'zymase', 'zython', 'zythum', 
]

if (CONFIG.normalization) {
  VALIDGUESSES.forEach(
    (val, i) => (VALIDGUESSES[i] = val.normalize(CONFIG.normalization))
  )
}
